function checkWaste() {
    let input = document.getElementById("wasteInput").value.toLowerCase();
    let result = document.getElementById("result");

    let biodegradable = ["banana peel", "food", "vegetable", "fruit", "leaf","banana peel",
        "apple core","orange peel","mango peel","grape stems","watermelon rind","papaya peel",
        "pineapple skin","coconut shell","coconut husk","lemon peel","lime peel","pomegranate peel",
        "guava leaves","vegetable peels","potato peel","onion skin","garlic skin","carrot tops","cabbage leaves",
        "cauliflower leaves","spinach stems","tomato scraps","cucumber peel","pumpkin rind","beetroot peel","radish leaves",
        "corn husks","pea pods","bean pods","egg shells","tea leaves","tea bags","coffee grounds","used coffee filters",
        "bread crusts","rice leftovers","cooked pasta","spoiled food","leftover curry","fruit pulp","sugarcane bagasse",
        "nut shells","peanut shells","almond shells","walnut shells","dry leaves","grass clippings","flowers","wilted flowers",
        "plant stems","tree bark","small branches","twigs","garden weeds","fallen fruits","hay","straw","sawdust","wood shavings","wood chips","bamboo sticks","cotton waste","jute waste","wool scraps","silk scraps","natural fiber rope","paper napkins","paper towels","tissue paper","newspaper","cardboard","paper bags","paper plates","paper cups","paper egg cartons","uncoated paper","pizza box","paper packaging","sugarcane plates","bagasse bowls","bamboo plates","wooden toothpicks","wooden ice cream sticks","wooden chopsticks","compostable cutlery","dried herbs","herbal tea residue","coconut water residue","juice pulp","spoiled milk","curd waste","cheese scraps","fish bones","chicken bones","meat scraps","seafood shells","shrimp shells","crab shells","feathers","animal manure","cow dung","goat manure","horse manure","pet fur","human hair","nail clippings","cotton buds with paper sticks","natural sponge","latex balloons","dried seaweed","algae waste","mushroom stems","spoiled mushrooms","bread mold","compostable food containers","biodegradable packaging peanuts","palm leaves","banana leaves","areca palm plates","areca palm bowls","rice husk","wheat bran","millet husk","cocoa shells","sunflower husks","sesame stalks","mustard stalks","cottonseed hulls","soybean residue","tofu residue","molasses residue","fruit seeds","avocado pit","jackfruit rind","jackfruit seeds","sapota peel","custard apple peel","lychee peel","dragon fruit peel","kiwi peel","pear core","peach pit","plum pit","apricot pit","cherry stems","fig leaves","mint stems","coriander stems","curry leaves","lemongrass waste","basil stems","rosemary stems","thyme stems","sage leaves","dried petals","floral garlands","incense ash","wood ash","charcoal ash","compostable diapers","biodegradable sanitary pads","natural cork","wine cork","pencil shavings","eraser dust from natural rubber","cotton balls","linen scraps","hemp fiber waste","coir pith","coir rope","coconut fiber","reed mats","palm fiber","sisal fiber","mulberry leaves","lotus leaves","betel leaves","tamarind shells","date seeds","olive pits","melon seeds","sunflower stalks","maize stalks","sugar beet pulp","cassava peel","yam peel","sweet potato peel","okra stems","brinjal stems","bottle gourd peel","ridge gourd peel","drumstick leaves","moringa stems","ash gourd peel","snake gourd peel","turnip peel","lettuce leaves","celery scraps","parsley stems","dill stems","fenugreek leaves","amaranth stems"];
   
        let recyclable = ["plastic bottle", "paper", "glass", "can", "cardboard","paper","newspaper",
            "magazine","cardboard","corrugated cardboard","office paper","notebook paper","printer paper",
            "junk mail","paper bag","paper carton","cereal box","egg carton","paper tube","gift wrapping paper",
            "glass bottle","glass jar","clear glass bottle","green glass bottle","brown glass bottle","aluminum can",
            "steel can","tin can","food can","beverage can","aluminum foil","aluminum tray","metal lid","metal cap","scrap metal",
            "copper wire","iron rod","steel utensil","empty aerosol can","plastic bottle","PET bottle","HDPE bottle","water bottle",
            "soft drink bottle","milk jug","detergent bottle","shampoo bottle","conditioner bottle","plastic container","yogurt cup",
            "plastic tub","plastic jar","plastic lid","plastic cap","plastic bucket","plastic crate","plastic basket","plastic chair","plastic table","plastic toy","plastic hanger","plastic storage box","plastic drum","plastic flower pot","plastic tray","plastic cup","plastic plate","plastic spoon","plastic fork","plastic knife","plastic straw","plastic bag","ziplock bag","bubble wrap","plastic packaging","plastic film","stretch wrap","milk carton","juice carton","tetra pack","pizza box","shoe box","gift box","mailing box","book","textbook","hardcover book","paper envelope","catalog","brochure","flyer","calendar","telephone directory","sticky notes","index cards","greeting card","paperboard packaging","toilet paper roll","paper towel roll","glass perfume bottle","glass food container","glass medicine bottle","wine bottle","beer bottle","pickle jar","jam jar","sauce jar","metal spoon","metal fork","metal knife","metal pan","metal pot","biscuit tin","cookie tin","paint can","metal toolbox","wire hanger","aluminum bottle","empty ink cartridge","printer cartridge","CD","DVD","CD case","DVD case","old mobile phone","keyboard","computer mouse","computer monitor","laptop","desktop computer","tablet","charger cable","USB cable","earphones","headphones","power bank","electric wire","extension cord","small appliance","electric fan","blender","toaster","rice cooker","vacuum cleaner","coffee maker","light fixture","PVC pipe","plastic pipe","garden hose","plastic barrel","plastic pallet","plastic spool","foam packaging","clean Styrofoam","plastic egg carton","plastic medicine bottle","laundry detergent container","bleach bottle","dish soap bottle","spray bottle","cosmetic bottle","lotion bottle","deodorant container","mouthwash bottle","juice bottle","cooking oil bottle","vinegar bottle","plastic food storage container","ice cream tub","butter tub","margarine container","takeaway container","clean aluminum food tray","clean foil container","metal biscuit box","metal bottle cap","metal jar lid","old bicycle","bicycle tire rim","scrap brass","scrap aluminum","scrap stainless steel","wooden pallet","wood crate","wooden furniture","wood scraps","cork","wine cork","fabric scraps","cotton clothing","denim jeans","old towels","bedsheets","curtains","canvas bag","jute bag","rubber tire","printer paper scraps","shredded paper","construction paper","manila folder","paper cup",
            "paper plate","napkin","paper packaging"];

    let hazardous = ["battery", "chemical", "paint", "medicine","battery","alkaline battery","lithium battery",
        "car battery","button cell battery","rechargeable battery","lead-acid battery","fluorescent tube",
        "CFL bulb","LED bulb","mercury thermometer","mercury thermostat","paint","oil-based paint","paint thinner",
        "paint stripper","varnish","wood stain","solvent","adhesive","glue","epoxy resin","pesticide","herbicide",
        "insecticide","fungicide","rodent poison","weed killer","fertilizer","pool chemicals","bleach","ammonia cleaner",
        "drain cleaner","oven cleaner","toilet cleaner","disinfectant","aerosol can","empty aerosol can",
        "full aerosol can","air freshener spray","bug spray","motor oil","used motor oil","brake fluid","transmission fluid",
        "antifreeze","fuel","gasoline","diesel","kerosene","paint can with residue","ink cartridge","toner cartridge",
        "printer toner","photographic chemicals","nail polish","nail polish remover","hair dye","peroxide solution",
        "medical waste","used syringe","needle","lancet","bandage with blood","expired medicine","prescription medication","chemotherapy drugs","mercury-containing device","smoke detector","fire extinguisher","e-waste","mobile phone","laptop","desktop computer","television","computer monitor","keyboard","mouse","charger","power bank","cable","circuit board","hard drive","USB drive","CD","DVD","cassette tape","vape device","e-cigarette","nicotine cartridge","ink bottle","cleaning chemical","laboratory chemical","acid","alkali","battery acid","sulfuric acid","hydrochloric acid","acetone","turpentine","diesel container","fuel can","propane cylinder","butane canister","gas cylinder","charcoal lighter fluid","camp fuel","wood preservative","creosote","asbestos material","asbestos insulation","treated wood","tar","roofing chemicals","sealant","caulk with solvents","resin","fiberglass resin","chemical fertilizer","agricultural chemical","disinfectant wipe","sanitizer concentrate","pool chlorine","chlorine tablets","spa chemicals","mercury switch","thermostat sensor","electronic toy","remote control","electric toothbrush","electric shaver","microwave oven","refrigerator","air conditioner","washing machine","dryer","dishwasher","vacuum cleaner","printer","scanner","fax machine","router","modem","speaker","headphones","camera","camcorder","drone battery","solar battery","UPS battery","generator oil","oil filter","grease","contaminated rag","chemical container","solvent-soaked cloth","pesticide container","paintbrush with paint","wood polish","shoe polish","rust remover","metal cleaner","silver polish","car wax","engine cleaner","radiator flush","battery charger","fluorescent ballast","x-ray film","laboratory glassware","biohazard waste","infectious waste","sharps container","thermometer with mercury","broken CFL bulb","broken fluorescent lamp","adhesive remover","contact cement","spray paint","paint aerosol","fuel additive","degreaser","industrial cleaner","chemical drum","toxic household cleaner","refrigerant","freon-containing appliance","old thermostat","electronic cigarette battery","lithium-ion battery","corrosive cleaner","chemical waste","hazardous sludge","contaminated soil","used cooking oil mixed with chemicals","oil-contaminated absorbent","automotive battery","lead scrap","chemical spill residue","toxic resin","industrial solvent","laboratory reagent",
        "expired pesticide","medical sharps"];

    let eWaste = ["mobile", "laptop", "tv", "charger","mobile phone","smartphone","feature phone",
        "laptop","desktop computer","tablet","computer monitor","CRT monitor","LCD monitor","LED monitor",
        "keyboard","mouse","printer","scanner","photocopier","fax machine","router","modem","Wi-Fi router",
        "switch","server","external hard drive","internal hard drive","solid state drive","USB flash drive",
        "memory card","CD","DVD","Blu-ray disc","CD player","DVD player","Blu-ray player","television",
        "CRT television","LED television","LCD television","smart TV","radio","speaker","headphones","earphones","microphone","webcam","digital camera","camcorder","projector","gaming console","video game controller","joystick","power bank","charger","mobile charger","laptop charger","USB cable","HDMI cable","Ethernet cable","extension cord","power strip","battery","alkaline battery","rechargeable battery","lithium-ion battery","button cell battery","car battery","UPS battery","inverter battery","electric fan","ceiling fan","table fan","air conditioner","refrigerator","washing machine","dryer","microwave oven","induction stove","rice cooker","mixer grinder","blender","toaster","electric kettle","coffee maker","vacuum cleaner","electric iron","hair dryer","hair straightener","electric shaver","electric toothbrush","sewing machine","water purifier","air purifier","room heater","geyser","CFL bulb","fluorescent tube","LED bulb","smartwatch","fitness tracker","calculator","electronic toy","remote control","drone","GPS device","walkie-talkie","landline telephone","intercom system","alarm clock","digital clock","electronic weighing scale","blood pressure monitor","glucometer","thermometer","smoke detector","CCTV camera","security system","doorbell camera","printer cartridge","toner cartridge","ink cartridge","circuit board","motherboard","graphics card","RAM module","processor","cooling fan","heat sink","network card","sound card","TV remote","set-top box","satellite receiver","MP3 player","MP4 player","cassette player","VCR","tape recorder","electronic keyboard","synthesizer","UPS","stabilizer","voltage regulator","solar inverter","solar panel","electronic cigarette","vape device","battery charger","electronic adapter","wire","cable reel","electric switch","socket","extension box","electronic component","resistor","capacitor","transformer","old appliance","broken electronic device","damaged charger","discarded circuit board","electronic scrap","e-waste accessory","computer casing","CPU cabinet","electronic sensor","RFID device","barcode scanner","POS machine","ATM machine","biometric scanner","electronic display board","LED sign board","electronic meter","smart meter","electronic lock","tablet stylus","VR headset","AR headset","3D printer","electronic instrument","oscilloscope","multimeter","scientific calculator","electronic lab equipment","smart home device","voice assistant speaker","wireless charger","Bluetooth speaker","wireless earbuds",
        "portable speaker","home theater system","gaming headset","electronic gadget"];

    if (biodegradable.some(item => input.includes(item))) {
        result.innerHTML = "🌱 Biodegradable Waste<br>👉 Dispose in Green Bin";
        result.style.color = "green";
    }
    else if (recyclable.some(item => input.includes(item))) {
        result.innerHTML = "♻ Recyclable Waste<br>👉 Dispose in Blue Bin";
        result.style.color = "blue";
    }
    else if (hazardous.some(item => input.includes(item))) {
        result.innerHTML = "☠ Hazardous Waste<br>👉 Dispose in Red Bin";
        result.style.color = "red";
    }
    else if (eWaste.some(item => input.includes(item))) {
        result.innerHTML = "📱 E-Waste<br>👉 Take to e-waste collection center";
        result.style.color = "purple";
    }
    else {
        result.innerHTML = "❓ Unknown Waste<br>👉 Please check manually";
        result.style.color = "black";
    }
}